:schedule:
  RecurringRoundWorker:
    cron: '*/10 * * * *'
    description: 'Update round stats every 10 minutes'

  RecurringFixtureWorker:
    cron: '*/10 * * * *'
    description: 'Update fixture stats every 10 minutes'

  RecurringTeamWorker:
    cron: '*/10 * * * *'
    description: 'Update team stats every 10 minutes'

  RecurringPlayerWorker:
    cron: '*/10 * * * *'
    description: 'Update player stats every 10 minutes'

  Score:
    cron: '*/10 * * * *'
    description: 'Update fpl_team scores every 10 minutes'
    class: 'Score::Job'

  RecurringWaiverPicksWorker:
    cron: '0 */1 * * *'
    description: 'Check that the date is the same as the waier deadline so that picks can be processed.'
