:schedule:
  RecurringRoundWorker:
    cron: '*/10 * * * *'
    description: 'Update round stats every 10 minutes'

  RecurringFixtureWorker:
    cron: '*/10 * * * *'
    description: 'Update fixture stats every 10 minutes'

  RecurringTeamWorker:
    cron: '*/10 * * * *'
    description: 'Update team stats every 10 minutes'

  RecurringPlayerWorker:
    cron: '*/10 * * * *'
    description: 'Update player stats every 10 minutes'

  RecurringScoringJob:
    cron: '*/10 * * * *'
    description: 'Update fpl_team scores every 10 minutes'
    class: 'RecurringScoringJob::Job'

  RecurringExpireTradeGroupsJob:
    cron: '0 */1 * * *'
    description: 'Expire pending and submitted inter_team_trade_groups if the current round deadline time has passed'
    class: 'RecurringExpireTradeGroupsJob::Job'

  RecurringProcessWaiverPicksJob:
    cron: '0 */1 * * *'
    description: 'Process all waiver picks for the current round once the waiver pick deadline has passed'
    class: 'RecurringProcessWaiverPicksJob::Job'
